### ISSUE TITLE
Authenticationdate - bad hours formatting

### ISSUE THREAD

**Issue by GValFr35** [sbechet/loopback-component-cas#3]
file : protocol23.js

authenticationDate format is misconfigured. 
Unable to differentiate the morning to the afternoon.

`returnProfile.CAS3attributes.authenticationDate = moment(tgt.created).format("YYYY-MM-DDThh:mm:ss")`

Change from H12 to H24
YYYY-MM-DDT**HH**:mm:ss

**Comment by sbechet** [comment]
Commit done.
